### ISSUE TITLE
Release note on own set/rise position

### ISSUE THREAD

**Issue by LexSewuster** [magtimmermans/com.cyclone-software.sunevents#1]
In the releasenotes of 0.0.8 it is mentioned that "Options to put your own set/rise position of the sun" are added. 
I couldn't find any implementation of this option.  Are the release notes accurate on this ?

**Comment by magtimmermans** [comment]
Hi,
 if you go to settings of your homey and lookup sunevents you can find there how to set it up.

**Comment by LexSewuster** [comment]
COOL!!! :-) :-)
