### ISSUE TITLE
invalid date

### ISSUE THREAD

**Issue by satbopper** [magtimmermans/com.cyclone-software.sunevents#10]
in the version 0.1.8 if i look at the event times there is a invalid date for night ends and night starts

**Comment by magtimmermans** [comment]
Correct, for this time of year there is no valid date for.

**Comment by rnldnkp** [comment]
Isn't that kind of useless for an app like this?
It should always have something in there, could even be the last usefull time or the closes next event.

You cannot automate something based on variables which are not valid during several months a year.

Could you think of a solution?
