### ISSUE TITLE
Using Conditions more than once per Day

### ISSUE THREAD

**Issue by CyberSponk** [magtimmermans/com.cyclone-software.sunevents#11]
**Metadata**

* **Homey Version**: 1.5.6-RC8
* **Homey Log Code**: -
* **Smartphone Platform**: Andoid
* **Smartphone App Version**: -

**If related to a Homey App: Sun Events**
* **Homey App Version**: 0.1.8
* **Homey App Log Code**: -
* **Affected Devices (preferably product codes)**: -

**What did you try to achieve?**
Created two Flows: Both using e.g. _Dusk_ in the If-Column. One Flow with _Dusk -20_ and a second Flow with _Dusk -25_.

**What did you expect as result?**
That both Flows are executed and that both Trigger-Timers are shown in Homey Settings > Sun Events > Trigger-Times.

**What was the result?**
Homey Settings > Sun Events > Trigger-Times > Only one Trigger-Time is shown> That one with the later Time _Dusk -20_. Also only one Flow (_Dusk -20_) is executed.

**Any other remarks**
It seems that a Trigger-Time e.g. Dusk only could be used once per Day.

**Comment by magtimmermans** [comment]
This is already possible.
