### ISSUE TITLE
Request: support Azimuth conditions in My Sun Events

### ISSUE THREAD

**Issue by hans-github** [magtimmermans/com.cyclone-software.sunevents#14]
Hi,
I'd like Sun Events to support the definition of Azimuth conditions in My Sun Events, the same way as the current Altitude conditions are supported. 
Intended usage is for controlling the screens of buildings: only control the screens when they are in the azimuth range where they can receive direct sunlight.

**Comment by magtimmermans** [comment]
It is already there, see TAG

**Comment by hans-github** [comment]
Sun Events does provide the Azimuth value as a tag, indeed, but as far as I know this cannot be used for triggering. So my request is to support triggering flows when the Azimuth value changes.

In My Sun Events I'd like to be able to define named Azimuth events, value 0-360, that can then be used in the When-card of Sun Events to trigger a flow. You would only need a single name per Azimuth value, where there are two names per Altitude value change in the Current Sun Events app.

I would welcome any alternative solution for supporting Azimuth-based triggering.
