### ISSUE TITLE
Add i for information to cards

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [magtimmermans/com.cyclone-software.sunevents#15]
Hello,

There are several states at which it is possible to fill in a number.  I presume these numbers are minutes, but I cannot find anywhere where this is described.

I suspected it, but only after an issue here I saw that negative numbers are possible.

Please add documentation in at the following placed:
- In a card you can add i for information, when mous hoverign over the information is shown. At least tell that the unit is minutes and that it should ne an integer between 0 and 999999 (? limit is not know, is there a limit?)) and that the number can be negative also.
- Add this to the app description in the app store of Homey.
- Add this to the release notes / info page on Github.

Thanks in advance, it will help others to understand the usage of the app.

Regards, Marco

**Comment by magtimmermans** [comment]
Well, basically it should be in the field where you type the number. If there is nothing you will see the description. I will add it anyhow.
