### ISSUE TITLE
Unable to install on Homey 2.0.0 RC2

### ISSUE THREAD

**Issue by mhoogenbosch** [magtimmermans/com.cyclone-software.sunevents#16]
Unable to install the app on the RC firmware of 2.0.0, it gives an error message saying: object OBJECT.

Don't know what it means, but it is not working.

**Comment by magtimmermans** [comment]
Did you install the beta version? As i have it up and running here.

**Comment by mhoogenbosch** [comment]
Nope, did not have the beta installed nor tried. Did not see it untill you mentioned :) beta installs though CLI just fine. Maybe add it on the apps.athom.com as beta? Tnx for your help.

**Comment by magtimmermans** [comment]
Well it is but waits for approval:)

**Comment by mhoogenbosch** [comment]
right, that tents to take time. It works tnx very much. Excpecially nice due to the fact the sunrise flows don't work anymore with the default flows.

**Comment by mhoogenbosch** [comment]
I can’t seem to get a flow triggered, I created a flow with a trigger of night start, to send me a push notifications (test flow)... the test worked, but when the time was there no notification. You mentioned it worked at your place, am I doing something wrong? Using time offset of zero.

**Comment by magtimmermans** [comment]
I think it has a bug with the initial setup. When you wait until tomorrow I think it will work. Could you let me know?   0 is indeed correct.

**Comment by mhoogenbosch** [comment]
Yes will do

**Comment by mhoogenbosch** [comment]
hi, all events were listed in the app (triggered events) but none actually triggered. I'm still waiting for the last one which should get triggered at 18.29 and send me a push message (and set a variable 'nacht' to yes). I'll let you know. But if it does not get triggered, is there a way we / I can see why it doesn't get triggered?

**Comment by magtimmermans** [comment]
Hi, I am not sure if you have the latest app. But they broke the push message on ios. Secondly there is a problem with getting coordinates and therefor it is impossible to calculate the events. For me since the latest updates it also not work anymore.

**Comment by mhoogenbosch** [comment]
Ah that's why the push didn't get through.. but if i understnad correctly the app in the current state just doenst work because of the breakage? Simular to the default Sunrise events?

**Comment by mhoogenbosch** [comment]
I think everything works again (including push notifications), but installed the latest app of homey and I recieved the push message saying it is night. So i have strong believe it works!
