### ISSUE TITLE
New triggers

### ISSUE THREAD

**Issue by bergh-io** [magtimmermans/com.cyclone-software.sunevents#18]
It would be very usefull with two new trigger events: "Getting darker" and "Getting brighter". Or just one, "Sun event happened" with a tag that contains "darker/brigher" or something similar.

They can follow the other events so they wont be executed every minute or so, they don't have to be "realtime".

This would be very useful for dimming lights up and down to follow the light outside without having to have one flow for every event as you can't have multipel trigger in Then.

**Comment by magtimmermans** [comment]
Okay. Let me think about this. If there is an easy solution.

**Comment by bergh-io** [comment]
Thank you! 
One other possible solution can maybe be a tag with how much light there is (theoretically) i percentage (100% at noon, 0% at nadir) or something like that.

**Comment by magtimmermans** [comment]
Implemented
