### ISSUE TITLE
Works when inversed

### ISSUE THREAD

**Issue by BaldSim** [magtimmermans/com.cyclone-software.sunevents#19]
I started using sun events the other day on Homey 2.0. I wanted to set a condition to be from sunset started to sunrise ends. But it doesn't work unless I inverse the condition. So "It isn't between Sunset starts Sunrise ends" works for turning on a lamp night time, while "It is between sunset starts sunrise ends" doesn't. 

Do your have any idea what it could be due to? I'm using 0.2.2. Thanks for a great app!

**Comment by magtimmermans** [comment]
I think this might not work, as the sunset is for example on 17.00 and the sunrise (that day) on 8.00, but you want probably the 17.00 until the next day 8.00?

**Comment by BaldSim** [comment]
Exactly, I want it to work as you described, from one day to the other. Maybe I have to rethink how I use it.

**Comment by magtimmermans** [comment]
You could set a variable and use that.
