### ISSUE TITLE
Sun event timestamps

### ISSUE THREAD

**Issue by LuddesGarage** [magtimmermans/com.cyclone-software.sunevents#20]
Hello! In the Homey desktop application it was possible to see all Sun Events under the "Tags" dropdown in when managing Flows. These time stamps represented the local sun events depending on the location of the Homey. Now in the v2 mobile app that feature seems to be gone. Would be perfect if the time stamps was visible when selecting an sun event item on the sun event card.

**Comment by magtimmermans** [comment]
If I understand your question correctly, then this is unfortunately not possible. I hope the tags will be back :)
