### ISSUE TITLE
issue with the in between card

### ISSUE THREAD

**Issue by dvnwldn** [magtimmermans/com.cyclone-software.sunevents#21]
When I add an in between card like in the screenshot it says the and in between card condition is not true...
is this a bug or am I doing it wrong?
![tussenflow](https://user-images.githubusercontent.com/47627357/53762479-84913180-3ec8-11e9-84e5-da274789a3d5.png)

Thanks, Dennis

**Comment by magtimmermans** [comment]
Begin zonsondergang is today and einde zonsopgang is also today. But you would probably between today and tomorrow (during the night).  You need to solve this with a variable. Make flow with start zonsondergang and set the var night on true. And a zonsopgang and set the bar night false.

**Comment by dvnwldn** [comment]
thanks!
