### ISSUE TITLE
Duplicate Trigger Event labels

### ISSUE THREAD

**Issue by Veldkornet** [magtimmermans/com.cyclone-software.sunevents#23]
In version 0.2.3

I was making a new flow, and I discovered that the IF conditions have a duplicate label for one of the conditions. 

Het is na
Het is na
Het is tussen

I can see from the code that the first one is for "cond_sun_event" and the second for "cond_sun_event_time"... but in the app, it’s not clear to me what the difference between the two is. 

Idea to maybe update these labels? 

![5001EBFF-5D72-4CF4-A801-10A34EA16F3F](https://user-images.githubusercontent.com/10297361/54865409-ac581480-4d65-11e9-9543-8faf158b4c7c.jpeg)

**Comment by magtimmermans** [comment]
Fixed in 0.24
