### ISSUE TITLE
Request: Add offset to condition card, time between event X and Y

### ISSUE THREAD

**Issue by treecamp** [magtimmermans/com.cyclone-software.sunevents#24]
Hi Marcel,

Love the app, my compliments.
I'm using your app to enable and disable my lights in the hallway and office.

**IF** 
_Zonsondergang (-30)_
**THEN**
_Disable "lights on" flow._

I found your "AND" card, "Het is tussen".
I'm using the offset option that you have in the "WHEN" card.

Is it possible that you add this option to the "THEN" card as well?

Hope it's clear what i mean.

With kind regard,

Coen

**Comment by magtimmermans** [comment]
Hoi Coen,

Niet helemaal. Zeg maar even in het nederlands :)

**Comment by treecamp** [comment]
Oke, dankje!

De offset optie is wel aanwezig in de ALS kaart, en niet in de EN kaart:
![Schermafbeelding 2019-04-24 om 17 34 17](https://user-images.githubusercontent.com/34875500/56672783-4f7ab180-66b7-11e9-8ece-b110a84b35ab.jpg)
![Schermafbeelding 2019-04-24 om 17 34 38](https://user-images.githubusercontent.com/34875500/56672784-4f7ab180-66b7-11e9-8727-8d0b1f84f898.jpg)

**Comment by magtimmermans** [comment]
Done!
