### ISSUE TITLE
Geen persoonlijke gebeurtenissen in flows meer na update

### ISSUE THREAD

**Issue by BartDeWorm** [magtimmermans/com.cyclone-software.sunevents#25]
De zonnestanden app werd gisteren 22/05 automatisch geupdated.
Nu merk ik dat de persoonlijke gebeurtenissen die in de app ingesteld waren onder het tabblad ‘Gebeurtenissen’ niet meer zichtbaar zijn bij het aanmaken van een Flow.

**Comment by magtimmermans** [comment]
Ok. Welke versie van Homey gebruik je en zijn de gebeurtenissen nog wel zichtbaar in de settings scherm van de app?

**Comment by BartDeWorm** [comment]
Ik gebruik Homey versie 2.1.2.
En de gebeurtenissen zijn effectief nog zichtbaar in het settings scherm
van de App, heb zelf al eens een regel verwijderd en eens opnieuw
toegevoegd maar ik krijg deze gebeurtenissen dus niet te zien in de flows.

Bedankt voor de moeite!

Op do 23 mei 2019 om 18:04 schreef magtimmermans <notifications@github.com>:

**Comment by magtimmermans** [comment]
Ok, ik ga er na kijken.

**Comment by magtimmermans** [comment]
Fixed, app is aangemeld bij Athom. Naar aproval beschikbaar als beta.

**Comment by BartDeWorm** [comment]
Top! Bedankt.
Ik test het van zodra beschikbaar.

Met vriendelijke groeten,
Bart

Op do 23 mei 2019 19:33 schreef magtimmermans <notifications@github.com>:

**Comment by magtimmermans** [comment]
Hij is nu in de app store als beta

**Comment by BartDeWorm** [comment]
Super! Het probleem is hier in helemaal van de baan!
Hartelijk dank!

Met vriendelijke groeten,
Bart

Op vr 24 mei 2019 14:04 schreef magtimmermans <notifications@github.com>:
