### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Dgh1974** [magtimmermans/com.cyclone-software.sunevents#26]
Hi

My app crashes. I think its when using the “tussen” event card.

When sellecting tussen event “a” i can not sellect anything but the app shows the hourglass.

0.2.9 iphone

**Comment by magtimmermans** [comment]
Hi,

Can you prove an screenshot of your tussen condition?

**Comment by Dgh1974** [comment]
Hi marcel

Zie screens.

Na keuze a blijft deze hangen met een zandloper.


[image3.png]


[image1.png]

[image4.png]

Verstuurd vanaf mijn iPhone X

Op 18 jun. 2019 om 14:37 heeft magtimmermans <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi,

Can you prove an screenshot of your tussen condition?

**Comment by magtimmermans** [comment]
Hi,
I do not see the pictures only the name of the picture :)

**Comment by Dgh1974** [comment]
Hope this is better


![240801C9-88C2-4B2F-BB71-34E98ADFA70A](https://user-images.githubusercontent.com/51015473/59684238-e6587b80-91d9-11e9-85f1-195ade8531cf.png)
![8DFACDC5-32DA-4FE2-B03D-B57974759BB2](https://user-images.githubusercontent.com/51015473/59684239-e6587b80-91d9-11e9-87be-b3510846bf7b.png)
![F261B1F3-AF9D-44E4-ADA3-9FFD8EE4349C](https://user-images.githubusercontent.com/51015473/59684241-e6587b80-91d9-11e9-9d31-923cd83ec5ff.png)

**Comment by magtimmermans** [comment]
Do you have in the app settings maybe personal triggers?

**Comment by Dgh1974** [comment]
Thats version 0.2.9

**Comment by Dgh1974** [comment]
I have 1 sunset trigger in the settings. Butvthats auto detected i think. Using the apo with 6 flows. 

I know the “tussen” option worked before.

**Comment by magtimmermans** [comment]
If you install the latest version (0.3.0) then at least your app should not crash but the trigger "tussen" will probably not work. But I am not able yet to reproduce it. So this will take me some time.

**Comment by Dgh1974** [comment]
He Marcel

0.3.0 ... “tussen” is working again. 👍

Could a recovery be the cause. Had a new ziggo modem and had to add homey to new wifi network. Not 100% sure ... but noticed the “tussen” hanging after that.

**Comment by magtimmermans** [comment]
👍
