### ISSUE TITLE
Times doens't match between times and triggers

### ISSUE THREAD

**Issue by Markmenh** [magtimmermans/com.cyclone-software.sunevents#29]
![2020-01-17 15_32_14-Homey Developer](https://user-images.githubusercontent.com/12759479/72619898-917f0e00-393e-11ea-9198-493b1ed13cd7.jpg)

![2020-01-17 15_30_16-Homey Developer](https://user-images.githubusercontent.com/12759479/72619851-77ddc680-393e-11ea-8628-5f8862c35ebe.jpg)

The times between times and triggers are different?
I also noted this morning the "zonsopgang" was one hour earlier than mentioned at the "tijden" tab. I have the time set to 0.
![2020-01-17 15_37_00-Homey Flow](https://user-images.githubusercontent.com/12759479/72620254-40234e80-393f-11ea-9b09-cb774e8e35fc.jpg)

**Comment by magtimmermans** [comment]
Welke versie is dit? Ik kan het namelijk niet reproduceren. Als je de trigger eens aanpast naar 1 min offset wordt de lijst in de trigger tab dan aangepast? Kan je mij ook de flow van de zonsopgang mailen?
