### ISSUE TITLE
Date label not correct

### ISSUE THREAD

**Issue by WimHe** [magtimmermans/com.cyclone-software.sunevents#3]
When using the "Date" label from a Sun Event trigger in a Voice action, Homey interprets the day and month in reversed. Today, December, 9 is spoken by Homey as the 12th of September.
I had a look at the code but my Java Script knowledge is. as yet, insufficient to come up with the correct solution.

![sun_events_date_error](https://cloud.githubusercontent.com/assets/17146684/21052544/d9d67324-be25-11e6-9a40-d47cd14ff79f.PNG)

**Comment by magtimmermans** [comment]
mmh, Is your homey in English setup?

**Comment by WimHe** [comment]
Yes it is.

**Comment by magtimmermans** [comment]
Ok. I will check what is wrong there.

**Comment by magtimmermans** [comment]
I found this issue. Unfortunately Homey does not give locale information and for me there is no way to retrieve this. So if I fill in 'en' it will assume United States format. So i have made a temporary hack. I will publish this fix today.

**Comment by magtimmermans** [comment]
Published
