### ISSUE TITLE
After update v0.3.5 triggers are missing

### ISSUE THREAD

**Issue by dirkg173** [magtimmermans/com.cyclone-software.sunevents#30]
Hello Marcel,
For example, if I select the sun event "It is between..." in the "And..." section, it is no longer possible to select the combination "It is between sunrise (Event A) and sunset (Event B) on the same day". For event B only triggers which refer to the following day appear, but I feel it is absolutely necessary to be able to use two triggers for one and the same day.
Why was this changed? Can you add the missing events again?
Thank you
Dirk

![D2ABBE36-B6CE-486D-B411-7D3476FD5562](https://user-images.githubusercontent.com/40319629/74006213-407d9b00-497b-11ea-9f1a-fe6d43fdc71e.jpeg)
![390A0249-EE65-46C4-B420-5C3D38B99A9E](https://user-images.githubusercontent.com/40319629/74006255-6440e100-497b-11ea-95cc-90758faaf85c.jpeg)

**Comment by magtimmermans** [comment]
Hi, Yes. That was a bug. It is already reverted but waits in the store for approval.

**Comment by JPe2** [comment]
Still waiting for approval after 13 days?

**Comment by dirkg173** [comment]
Update (Version 0.3.7) was released on 13.02.2020. Bug is fixed.
