### ISSUE TITLE
Solar events with random delay

### ISSUE THREAD

**Issue by dirkg173** [magtimmermans/com.cyclone-software.sunevents#31]
Hello Marcel

I would like to open or close my roller shutters mainly on the basis of sun events.
To prevent the roller shutters closing always exactly at sunset, a random time delay (e.g. 0-30 minutes), which is already present in many device actions, would be helpful. A kind of presence simulation.
If I would realize the random time delay only via the roller shutters, it could happen that neighboring shutters would close with a time delay of e.g. 30 minutes, which of course does not correspond to the norm.
My idea is to close the roller shutters at sunset with a random time delay of 0-30 minutes. I would then let the individual shutters close one after the other with a time delay of 0-10 seconds (like manual closing).

Is this possible?

I hope it is understandable what I mean, what my idea is. English is not my mother language.

Many thanks in advance
Greetings
Dirk

**Comment by magtimmermans** [comment]
I think you need to store the sunset event in a variable and add random time to it and test this variable.
