### ISSUE TITLE
Sun events doesn’t trigger when tags (variables) are used

### ISSUE THREAD

**Issue by dirkg173** [magtimmermans/com.cyclone-software.sunevents#32]
Hello, Marcel,
with the sun events app I have the problem that the card "sun events (offset in min)" in the field "offset in min" only "real" numeric values are accepted. Real values from variables (tags) are not supported. Therefore the app does not trigger.
Is it possible to correct the bug?
Many thanks in advance!
Dirk

**Comment by dirkg173** [comment]
If the use of tags would work, request #31 would be obsolete.

**Comment by magtimmermans** [comment]
No, This isn't a bug. You can only use numeric values.
