### ISSUE TITLE
Request: Make user defined events available as global tags

### ISSUE THREAD

**Issue by Berrie1** [magtimmermans/com.cyclone-software.sunevents#34]
Hi, great app!

A request though: Is it possible to make the user defined events available as global tags such that the time value can be used in any flow?

Another minor thing regarding the flow cards: Can the offset value be put in parenthesis such that it matches the description "event (offset in min)"?

Regards,
Berrie

**Comment by magtimmermans** [comment]
Hi,
The first item is fixed: https://homey.app/a/com.cyclone-software.sunevents/test/
The second item is impossible as Homey deals with this.

**Comment by Berrie1** [comment]
Hi,

First item: Thanks, seems to work fine.
Second item: No text can be added in between like "with offset of"? It looks a bit odd "sunrise 0".

Regards,
Berrie

**Comment by magtimmermans** [comment]
Maybe I misunderstood you but on which spot do you see this?

**Comment by magtimmermans** [comment]
Hi,

I have an updated version but you need to refresh the flows to see the text change.

https://homey.app/nl-nl/app/com.cyclone-software.sunevents/Zonnestanden/test/

**Comment by Berrie1** [comment]
Hi,

This indeed gives a desired result in the flow cards but I see that in all triggers and tags the text "with offset" has been added. I don't think that everyone will appreciate that.
It becomes clear that no text can be added in the flow cards in between the event name and offset value. So I will just live with that.
Thanks for your support!

Regards,
Berrie
