### ISSUE TITLE
Sunevent triggers up to 3 times

### ISSUE THREAD

**Issue by dirkg173** [magtimmermans/com.cyclone-software.sunevents#35]
A sunevent like sunrise or sunset triggers flows up to 3 times. I have not tried other events.
I found it out like this:
If...
Sunrise or Sunset (Offset = 0)
Then...
Send Notification

Homey sends me 2 or 3 notifications then. With the Homey build in Sunrise/Sunset I receive only 1 notification.

**Comment by magtimmermans** [comment]
Do you have a Homey normal or a Pro? Because I cannot reproduce this.

![image](https://user-images.githubusercontent.com/17949840/95053874-518cd080-06f1-11eb-8c84-e1db9151f082.jpeg)

![image](https://user-images.githubusercontent.com/17949840/95053910-5b163880-06f1-11eb-94b9-14e68b2b82a1.jpeg)

**Comment by magtimmermans** [comment]
I have made a change but I am not sure it helps with you. Please test this:
https://homey.app/nl-nl/app/com.cyclone-software.sunevents/Zonnestanden/test/

**Comment by dirkg173** [comment]
I have a Pro. And other user have the same problem ([Community](https://community.athom.com/t/fibaro-dimmer-2-double-tap-starts-flow-twice/35405/7?u=fantross)). But I will test it and let you know.
Many thanks for the quick response.

**Comment by dirkg173** [comment]
Yesterday evening und this morning sun events triggered 3 times again. Homey's build in solution not.
Diagnostic report: cfd3c56c-c140-483e-812e-ae675e6b69aa

![image](https://user-images.githubusercontent.com/40319629/95165203-d2a89e00-07ab-11eb-8cb3-bee7cffa926d.jpeg)

**Comment by magtimmermans** [comment]
Really strange. If I look to the trace dump I see 3 sunrise events and 3 sunset events. I see that the other user has this also with a different app. I almost thinking this is a bug into homey but then you should have this often. I will check if I make use of an older sdk call. Unfortunately I do not have an pro so it is hard to reproduce.

**Comment by dirkg173** [comment]
> but then you should have this often

If the sunevent app normally triggers light or shutter flows, I don't see whether the flow has been triggered multiple times. The lights go on and the shutters go down as they should. So I can't know that the flows might be triggered multiple times.
But I will add notifications to theses flows. Let's see if the flows are triggered multiple times.

**Comment by magtimmermans** [comment]
Hi, Okay. I am now really curious to find it. The weird part is also that the three triggers at the exact same time.

**Comment by dirkg173** [comment]
Here are the "new" Flows.
Green: Homey build in sunset, triggered 1x
Yellow, Red, Blue: Sunevent app trigger time = sunset (offset = 0), triggered 3x
Black: Sunevent app trigger time = sunset (offset = 10), triggered 1x

![image](https://user-images.githubusercontent.com/40319629/95244368-25b53c00-0812-11eb-960f-44f4cfd7fcb4.jpeg)

**Comment by dirkg173** [comment]
Every morning at sunrise und every evening at sunset the flows are triggered 3 times. Only the flow with the homey build in sunrise/sunset and the flow with the sunevent app and an offset of 10 minutes is triggered 1 time.
What can I do? Should I send you a diagnostic report?

Diagnostic report: dadaad0a-d7e9-40e4-9d91-93681911fbc8

**Comment by magtimmermans** [comment]
Could you also try some other events. To make sure that all events occur 3 times.

**Comment by dirkg173** [comment]
Except of two testflows and one productive flow with sunrise/sunset offset 0 I replaced all other action cards (sunevents sunrise and sunset without offset) with the Homey Build In solution. 
I created testflows with Sunevents with "Nautical Dawn" and "Beginning Golden Hour" (both without offset).
Result:
- the 2 testflows with sunrise/sunset (offset 0) were not triggered??
- the testflows "Nautical Dawn" and "Beginning Golden Hour" (both without offset) were triggered only 1x each

Diagnostic report no.: adb3b842-73d5-4fd6-af11-f3d620e1da36

I cannot 100% reproduce if I made a mistake, sorry.

**Comment by magtimmermans** [comment]
Extreme weird. All events are triggered by the same function. Maybe athom can supply me a Homey Pro for testing ;-). I will try to debug some more.

**Comment by dirkg173** [comment]
Maybe you could try 10+ Flows with sunset and 10+ Flows with sunrise. Based on my recent changes and results, the problem may have something to do with the number of flows.

**Comment by magtimmermans** [comment]
Okay, will try this.

**Comment by dirkg173** [comment]
> * the 2 testflows with sunrise/sunset (offset 0) were not triggered??

I found the mistake I made. I switched the lux sensor von ConBee II Stick to Homey (Aqara App), so the device was missing. I solved the problem and will have a look on it, if is triggered 1 or 3 times again.

**Comment by magtimmermans** [comment]
Hi, I have tested a lot and made some small modifications. I think multiple triggers should be gone. I have also found out that when I have the same trigger 10 times and write this to the notes. Not all are seen. When I instead increment a variable with the logic card then it works fine. So somehow the notes had a kind of spam filtering (too much from the same app or so).
you can test this version: https://homey.app/nl-nl/app/com.cyclone-software.sunevents/Zonnestanden/test/

**Comment by dirkg173** [comment]
This is what I tested today:
5 flows at Sunset begins
8 flows at Sunset

Result: none of these flows were triggered more than once.

Tomorrow I will add some more flows with „@Sunset“ and let you know what will happen.

**Comment by dirkg173** [comment]
I have now tested 19 flows with sunset (offset 0) and no flow was triggered multiple times.
Most of them were simple flows (@sunset -> notification) but I hope that the problem is solved.

**Comment by magtimmermans** [comment]
Solved
