### ISSUE TITLE
Wrong time for "Sunset ends"

### ISSUE THREAD

**Issue by dirkg173** [magtimmermans/com.cyclone-software.sunevents#36]
The time for "sunset ends" (Sonnenuntergang endet) is earlier than the time for "sunset" (Sonnenuntergang).

![D8D06B4F-620C-40EB-95CA-81437DB474FC_1_201_a](https://user-images.githubusercontent.com/40319629/95195504-eae1e280-07d6-11eb-906a-43ee57ae6e2b.jpeg)

**Comment by magtimmermans** [comment]
Fixed, a german translation error
