### ISSUE TITLE
[Feature] Add Carcadian lighting light dim level and temperature

### ISSUE THREAD

**Issue by TedTolboom** [magtimmermans/com.cyclone-software.sunevents#37]
Hi Marcel,

Would it be possible to extend your great app with direct output of the dim level and light temperature based on the Carcadian rythm? Similar to https://community.home-assistant.io/t/circadian-lighting-custom-component/61246?

All components are already included into your app.

Best regards,

Ted

**Comment by magtimmermans** [comment]
Well, at least I will take a look to it if this is possible. Something for the weekend 😃

**Comment by magtimmermans** [comment]
I have done a first test, I have now token values (Kelvin, and Red, Green, Blue) and the lightpercentage already exists. I am not sure how you want to present it?

**Comment by magtimmermans** [comment]
Unfortunatly I am not able to publish as I got forbidden back during uploading files. It is party published :(

**Comment by magtimmermans** [comment]
https://homey.app/nl-nl/app/com.cyclone-software.sunevents/Zonnestanden/test/
Please check. The values are written in TAG. But I am not sure if this is convenient.
