### ISSUE TITLE
It’s between...

### ISSUE THREAD

**Issue by iFac3** [magtimmermans/com.cyclone-software.sunevents#38]
Hi Marcel,

Awesome app, thanks for this.

I’ve found a bug. If I use “it is between” in the “and...” section, it blocks the flow even in the right period of the day.

For example it blocks now, at 22:00 at Hungary in this flow:

https://homey.app/f/90RfBo

App shows that dawn will come at AM6:38 tromorrow, while dusk is not listed anymore since it passed.

Could you please look into it?

Thanks!

**Comment by magtimmermans** [comment]
Hi, 

Yes, I will do it at the weekend. But I think it is because it compares dusk and dawn from today. Which is not happening. So I think you need to select dawn tomorrow.

**Comment by iFac3** [comment]
Thanks for quick reply!

I’m gonna check it before weekend, then let you know.

Rgds,

Gergely.

**Comment by iFac3** [comment]
I’ve just tested. Same result.

https://homey.app/f/nsJXFo

**Comment by magtimmermans** [comment]
Okay, I will check in the weekend.

**Comment by magtimmermans** [comment]
Unfortunately, this is an issue that can be resolved. I have removed tomorrow's events. The problem is that when it is midnight today's Dusk will be changed. Therefore the condition would change and not work. New version:

https://developer.athom.com/apps/app/com.cyclone-software.sunevents/build/21

**Comment by iFac3** [comment]
Thanks for checking and resolving!

Rgds,

Gergely.
