### ISSUE TITLE
Error on Apps settings page.

### ISSUE THREAD

**Issue by Dijker** [magtimmermans/com.cyclone-software.sunevents#4]
Homey 1.0.4
Sun Events 0.1.2

Stack trace:
TypeError: Cannot read property 'compare' of undefined
at check [as _onTimeout] (/sunevent.js:254:49)
at Timer.listOnTimeout (timers.js:92:15)
Exit code: 1
Exit signal: null

Don't know what happend...

**Comment by magtimmermans** [comment]
Hi,

Did you make your own event and used it? And maybe deleted this event again?

**Comment by Dijker** [comment]
So fast ;-) 
Thanks!
Yes I have an own event. 
Event A was 3 gr.
Created an Event B and changed it twice for time info.
Today I changed A from 3 degrees to 6. Maybe around the time it should have  triggered... 
Does that explain enough? 
Maybe you could add a check in the code to prevent these crashes, if not no big deal ;-) Thanks!!

**Comment by magtimmermans** [comment]
Yes, OK. I will update the code.

**Comment by magtimmermans** [comment]
I hope this is fixed now
