### ISSUE TITLE
Request: Add as condition "altitude is between A and B".

### ISSUE THREAD

**Issue by Berrie1** [magtimmermans/com.cyclone-software.sunevents#40]
Hi,

Currently the altitude is not available as condition. Next to this, it would be nice to be able to define that the value should between A and B, instead of creating two separate cards (one for larger than and one for smaller than).

Regards,
Berrie

**Comment by Berrie1** [comment]
Dear Marcel,

Is it possible to add the altitude as condition?

Regards,
Berrie

**Comment by magtimmermans** [comment]
Sure, If I have some free time I will add it.

**Comment by magtimmermans** [comment]
Hi,

Please check here for a test version: https://homey.app/a/com.cyclone-software.sunevents/test/
let me know if it is okay then I will close the case and publish this to live.

**Comment by Berrie1** [comment]
Thanks! It works fine.
Currently the altitude has to be literally in between the values, but it is debatable whether the values itself should also be included.

**Comment by magtimmermans** [comment]
well, between means really between the numbers and not included. But we will see. Hopefully, people understand.
