### ISSUE TITLE
Zonnestand avondschemering werkt niet

### ISSUE THREAD

**Issue by SlyNL** [magtimmermans/com.cyclone-software.sunevents#41]
De scène start niet wanneer ik gebruik maak van “avondscherming”
![1E436006-BFAD-4B4F-9C27-5387FC071C02](https://user-images.githubusercontent.com/70058541/114081378-c7464480-98ac-11eb-9464-dfb3b4228bfa.png)
![C1F238CC-C283-4F85-BC3C-7B50B4A6B039](https://user-images.githubusercontent.com/70058541/114081391-cb726200-98ac-11eb-8224-6a72d860cd11.png)

**Comment by magtimmermans** [comment]
Hallo,

Dat is raar, ik heb hier soort gelijk draaien. Zou bij de configureer App  en dan de tab trigger eens kunnen kijken wat daar staat?

**Comment by SlyNL** [comment]
Lijkt normaal. Alleen op t tijdstip reageert de scène niet. 
![3114D233-5D29-4F30-9031-956B86463E2C](https://user-images.githubusercontent.com/70058541/114161971-ec789880-9928-11eb-8cb0-73c1d88718fe.jpeg)

**Comment by magtimmermans** [comment]
Tijden kloppen.

**Comment by SlyNL** [comment]
> Tijden kloppen.

Inderdaad dat had ik ook al gezien. Want de zonsondergang werkt wel t is specifiek de schemering.

**Comment by magtimmermans** [comment]
Zou je even een korte test script kunnen maken met de avondschemering en dan een bericht naar je zelf sturen? Ik zal ook even testen vanavond, Maar ik ben vrij zeker dat het zou moeten werken.

**Comment by SlyNL** [comment]
> Zou je even een korte test script kunnen maken met de avondschemering en dan een bericht naar je zelf sturen? Ik zal ook even testen vanavond, Maar ik ben vrij zeker dat het zou moeten werken.

Is aangemaakt, ik hou je op de hoogte

**Comment by SlyNL** [comment]
> > Zou je even een korte test script kunnen maken met de avondschemering en dan een bericht naar je zelf sturen? Ik zal ook even testen vanavond, Maar ik ben vrij zeker dat het zou moeten werken.
> 
> Is aangemaakt, ik hou je op de hoogte

Test scène werkt wel, schiet mij maar lek,
Morgen dan maar even een keuze scène opbouwen. 

Thanks voor je hulp

**Comment by magtimmermans** [comment]
Succes!
