### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Itsmmai** [magtimmermans/com.cyclone-software.sunevents#42]
Hi Marcel, can you help me out. I live near Leiden Netherlands 🇳🇱 and I would like my homey to open and close my blinds during a particular sun angle. Now I use my apple to close until 3 hours after sunrise but that doesn’t do the trick for a long time. Is there a smart way to do this with zonnestand?

Thanks for helping me
Ab

Ow btw, I know you are Dutch as well but in English more people are helped 😉

**Comment by magtimmermans** [comment]
Hi,

To have it perfect you need to have more de sort like temperature and lux. But I use the azimuth to make sure that the sun is at a the right angle to hit the window. I also use altitude for the correct hight. So I checked the azimuth on a sunny day and the altitude that I would like to close the blinds and make a trigger for this. I did the same for open the blinds again.

But nowadays I use more sensors and this works perfect. I use 2 temp sensors (one placed in shadow and on in the sun), lux meter, azimuth, altitude and rain sensors. Based on the difference between the shadow temp and sun temp I know the strength of the sun and with the other sensors I use this for closing the blinds (before this way of measuring I used the solar power). For final opening again I use lux, azimuth and altitude. I also use in between opening when it is raining or shadow for a while. For me this all growth in time. In the beginning this was a very simple trigger but now it is a bit more complex. 

Hope this info helps you.

**Comment by Itsmmai** [comment]
Cewl. I also start experimenting with the flows. Do you want to share a flow? Wondering what you use for shadow and rain or like today cloudy ☁️?

________________________________
Van: magtimmermans ***@***.***>
Verzonden: Saturday, April 24, 2021 8:24:08 AM
Aan: magtimmermans/com.cyclone-software.sunevents ***@***.***>
CC: Ab Helversteijn-Smit ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.sunevents] Question (#42)


Hi,

To have it perfect you need to have more de sort like temperature and lux. But I use the azimuth to make sure that the sun is at a the right angle to hit the window. I also use altitude for the correct hight. So I checked the azimuth on a sunny day and the altitude that I would like to close the blinds and make a trigger for this. I did the same for open the blinds again.

But nowadays I use more sensors and this works perfect. I use 2 temp sensors (one placed in shadow and on in the sun), lux meter, azimuth, altitude and rain sensors. Based on the difference between the shadow temp and sun temp I know the strength of the sun and with the other sensors I use this for closing the blinds (before this way of measuring I used the solar power). For final opening again I use lux, azimuth and altitude. I also use in between opening when it is raining or shadow for a while. For me this all growth in time. In the beginning this was a very simple trigger but now it is a bit more complex.

Hope this info helps you.

**Comment by magtimmermans** [comment]
Hi, I moved 90% of my environment to Home Assistant so, my flows are not running anymore on Homey. But it is not that difficult. You can make a variable like temp_sun-temp_shadow->temp_diff. This value gives you the strength of the sun (or if you have solar pannels, you can use this also).
