### ISSUE TITLE
Adding card "Azimuth is between"

### ISSUE THREAD

**Issue by dirkg173** [magtimmermans/com.cyclone-software.sunevents#43]
Hi Marcel,

I saw that you added cards for the altitude of the sun. Thanks for that!
Could you also add a "Azimuth is between" card for the "And..." section?
That would be great!

Best regards
Dirk

**Comment by magtimmermans** [comment]
Added as beta, please test:
https://homey.app/a/com.cyclone-software.sunevents/test/

**Comment by dirkg173** [comment]
Made a little flow:
When
Azimuth changed
And
Azimuth is between 190 and 195
Then
Push (with actual Azimuth)

I received 4 pushs with 191, 192, 193 and 194.
So it seems that it works as it should.

Thx

**Comment by magtimmermans** [comment]
Great, then I will publish it to live.
