### ISSUE TITLE
Carcadian lighting light Values Question

### ISSUE THREAD

**Issue by clipse2004** [magtimmermans/com.cyclone-software.sunevents#44]
Hi,
I have seen that your app should support Carcadian lighting.
I can't quite get to grips with the flows though.
The sunlight has changed -> write variable in day, but I can not use the lamps because the value is too high. Currently, for example, the sunlight in the variable is 24.
How do I get it, that the switched on lamps take this into account accordingly?  
Thank you!

**Comment by magtimmermans** [comment]
Hi,

For know the calculation will give the following Tokens:

Kelvin, red, green, and blue. With this, you should be able to change the light intensity and / or the color
