### ISSUE TITLE
character encoding problem in French

### ISSUE THREAD

**Issue by m4xx75** [magtimmermans/com.cyclone-software.sunevents#46]
Hello,
I have a character encoding problem in French (é => �)

![Screenshot_20210604-015417_Homey](https://user-images.githubusercontent.com/31291478/120726252-f1e10200-c4d7-11eb-971e-61c0d1e939a0.jpg)

Thanks !

**Comment by magtimmermans** [comment]
Aha, Okay let me check.

**Comment by magtimmermans** [comment]
The person that converted to French had not UTF 8 format enabled. Now I have weird chars. Could you edit the file? I will then make a new release with it.
[fr.txt](https://github.com/magtimmermans/com.cyclone-software.sunevents/files/6602569/fr.txt)

**Comment by m4xx75** [comment]
Thank you for your quick feedback!

This is good news, the problem will be fairly easy to correct :)
Here is the modified file attached.

Thank you so much !
[fr_patched.txt](https://github.com/magtimmermans/com.cyclone-software.sunevents/files/6603409/fr_patched.txt)

**Comment by magtimmermans** [comment]
Please test this version to check if it is fixed: https://homey.app/a/com.cyclone-software.sunevents/test/

**Comment by m4xx75** [comment]
It's perfect, thanks for the job! 😊👍🏻

**Comment by magtimmermans** [comment]
No problem
