### ISSUE TITLE
active triggers does not appear and logging tab inaccessible 

### ISSUE THREAD

**Issue by m4xx75** [magtimmermans/com.cyclone-software.sunevents#47]
Hello!

Since update 0.8.1 (by the way, thank you again) I notice that the active triggers no longer appear:
![Screenshot_20210606-230349_Homey.jpg](https://user-images.githubusercontent.com/31291478/120940059-7c657380-c71b-11eb-99c7-ab1c4692d2f6.jpg)

Also, i noticed another problem but which was already present in 0.8.0.
I  can't display the logging tab:
![Screenshot_20210606-230422_Homey.jpg](https://user-images.githubusercontent.com/31291478/120940066-8b4c2600-c71b-11eb-81b9-c1a2669570ba.jpg)

The screen is still blocked on the previous selection.

Thanks !

**Comment by magtimmermans** [comment]
Mmh, must be the homey update. Will be next weekend when I can check it.

**Comment by m4xx75** [comment]
OK, thanks !

For information, before opening the issue I tried to uninstall the App, delete the concerned flows, restart Homey, reinstall the App and recreate the flows. 

It did not work!
Have a good week 😉

**Comment by m4xx75** [comment]
Hello !

Since this morning I have visualized the active triggers again. I imagine there is a periodic refresh.

No change for logging.

**Comment by magtimmermans** [comment]
Yes, it have.

**Comment by m4xx75** [comment]
Hello,

You closed the issue but the loggins tab is still not accessible :(

**Comment by magtimmermans** [comment]
Aha, sorry. Ok will check this in the weekend.

**Comment by magtimmermans** [comment]
https://homey.app/a/com.cyclone-software.sunevents/test/
please test.

**Comment by m4xx75** [comment]
Again, thanks for the job! It works.
I say first click on the logging button, then the logs are displayed:

![Screenshot_20210612-165156_Homey.jpg](https://user-images.githubusercontent.com/31291478/121780067-f6c04880-cb9e-11eb-9f9b-a20f4d63a70f.jpg)

![Screenshot_20210612-165427_Homey.jpg](https://user-images.githubusercontent.com/31291478/121780070-f922a280-cb9e-11eb-8499-0c44bc4b5fde.jpg)

Thanks ;)
