### ISSUE TITLE
Using Offset w/ Variables does not seem to work

### ISSUE THREAD

**Issue by Pleister023** [magtimmermans/com.cyclone-software.sunevents#48]
Hi, I want to use a variable offset instead of a fixed number. But when using eg. Sunset or Start golden hour with an offset using that variable, it does not trigger the flow. Without offset, or a fixed offset (so number instead of var) it works perfectly.
The variable is calculated like this: _{{round((-0.5*cos(iDayOfYear*(pi/180)))*60,0)}}_ which always results in a whole number between -30 (winter) and +30 (summer), which should in my opinion be a correct number for the offset value.
When testing the flow, everything works as intended. It's just that the flow is not triggered at all when it should.
What am I doing wrong?
Regards,
Remco.

**Comment by magtimmermans** [comment]
There is a bug in homey that give the wrong values back using the function I use when to get the values of variables. I am waiting for a fix for this.

**Comment by Pleister023** [comment]
Top. Bedankt. 
Ik wacht af. 

Verstuurd vanaf mijn iPhone

**Comment by PeterKawa** [comment]
Additional: Someone reported the Sonos volume setting, when using a var as volume level, has the exact same issue. 
(Sonos is an app by Athom by the way)

**Comment by magtimmermans** [comment]
It is a know issue. Homey needs to fix this but it was a difficult one. I reported this already months ago.

**Comment by magtimmermans** [comment]
This issue is still in homey and not been fixed

**Comment by PeterKawa** [comment]
Thanks for your effort! 
Best, Peter
