### ISSUE TITLE
REQUEST: Support for Australia

### ISSUE THREAD

**Issue by smarthomesydney** [magtimmermans/com.cyclone-software.sunevents#49]
Hi mate.  
Thank you to the app.  Very handy for lighting.  🤟

My issue is when I go to use tags in flows (value) is set to Europe's time zone.  For example see screenshots.  Seasons are incorrect with winter been summer and vice versa.  It's reporting summer, but I am winter.

Is it possible to change the time zone on your app?  Don't see option in configure page.   

Also is it possible to use the current "season" tag in a when or and flow?  
Can there be an when/and value of "tag" =?

Thanks again mate

![Screenshot_20210816-102411_Homey](https://user-images.githubusercontent.com/25046666/129497307-819141ee-37a5-400f-871e-707d4e01229a.jpg)
![Screenshot_20210816-102354_Homey](https://user-images.githubusercontent.com/25046666/129497311-bb81f2a5-27c5-49fe-9db2-4e197e4e19da.jpg)

**Comment by magtimmermans** [comment]
Hi, I will take a look to it. For the seasons I am using a third-party package. I will try too fix it.

**Comment by magtimmermans** [comment]
Please check this test version, it is hard to test for me. So please let me know what is correct and still wrong.
https://homey.app/nl-nl/app/com.cyclone-software.sunevents/Zonnestanden/test/

**Comment by smarthomesydney** [comment]
Thank you mate!
That has done it! 👍 
Much Appreciated...

What did you change?

I was doing some digging and seemly the cause of the issue is a change to code by Homey.  With system date no longer returning local time instead defaulting to UTC time zone...
Below is how some other community devs are getting around it.

"const regex = /(\d\d):(\d\d):(\d\d)/;
const timeMatches = sys.dateHuman.match(regex)"
