### ISSUE TITLE
Azimut vs. Azimuth

### ISSUE THREAD

**Issue by PeterKawa** [magtimmermans/com.cyclone-software.sunevents#50]
Hi Marcel. Thanks for the great app. 
v.0.8.2
The (same) variable has different names somehow.
It doesn't seem to be a problem, but what's the thought behind it?
Testflow:
![Screenshot_20210907-193624_Homey](https://user-images.githubusercontent.com/74005072/132390692-ce5a3b13-3afd-4ff9-8ed9-fba9b2b26053.jpg)

Tags:
![Screenshot_20210907-185627_Homey](https://user-images.githubusercontent.com/74005072/132391118-c72b363d-e0d2-4526-9f4f-eb73a140d800.jpg)

Notification:
![Screenshot_20210907-195015_Homey](https://user-images.githubusercontent.com/74005072/132390741-b43bcdd8-ecb5-40e0-8ad0-2aabd9948eb6.jpg)

Cheers,
Peter

**Comment by magtimmermans** [comment]
Hi,

Mmh, are those both comming from my app?

Not seen this before 😃

Marcel Timmermans
Send from my iphone


Op 7 sep. 2021 om 20:10 heeft PeterKawa ***@***.***> het volgende geschreven:

﻿

Hi Marcel. Thanks for the great app.
v.0.8.2
The (same) variable has different names somehow.
It doesn't seem to be a problem, but what's the thought behind it?
Testflow:
[Screenshot_20210907-193624_Homey]<https://user-images.githubusercontent.com/74005072/132390692-ce5a3b13-3afd-4ff9-8ed9-fba9b2b26053.jpg>

Notification:
[Screenshot_20210907-195015_Homey]<https://user-images.githubusercontent.com/74005072/132390741-b43bcdd8-ecb5-40e0-8ad0-2aabd9948eb6.jpg>

Cheers,
Peter

**Comment by PeterKawa** [comment]
Yes they are indeed.
I was helping Martijn with testing the "Flow Checker" app. It also checks for variables. 
He noticed the different names for one variable inside your app, or something like that ;-)

It was a pure coincidence by the way. 2 flows with the Azimuth change as trigger reported a false positive. Which means, nothing wrong, but the flow checker app decided it was. ;-)

Op di 7 sep. 2021 20:40 schreef magtimmermans ***@***.***>:

**Comment by magtimmermans** [comment]
Hi,

OK, I will check in the weekend.

Marcel Timmermans
Send from my iphone


Op 7 sep. 2021 om 22:12 heeft PeterKawa ***@***.***> het volgende geschreven:

﻿

Yes they are indeed.

Op di 7 sep. 2021 20:40 schreef magtimmermans ***@***.***>:

**Comment by magtimmermans** [comment]
Hi, I checked this. The first one is the locale argument for the trigger. The value is passed when the trigger is active and you will get the current trigger value (which is the same as the second app Azimut value).
