### ISSUE TITLE
'Het is tussen' werkt niet meer

### ISSUE THREAD

**Issue by JeeMBe** [magtimmermans/com.cyclone-software.sunevents#51]
Ik gebruik de app zonnestanden/ de optie 'Het is tussen' 'Zonsondergang Offset 0' 'Zonsopgang Offset 0' om na het triggeren van een bewegingsmelder (gedurende die periode) een actie uit voeren. Deze optie werkt echter sinds een paar weken niet meer.

**Comment by magtimmermans** [comment]
Zonsondergang is rond 16.30 en zonsopgang is 8.30. Dus tussen 16.30 en 8.30 (zelfde dag) zal nooit triggeren.

**Comment by JeeMBe** [comment]
Ik ben niet echt duidelijk geweest lees ik, sorrie. Bij ALS 'de bewegingsmelder gaat aan' en bij EN vervolgens het is tussen etc..... en bij DAN de actie.

**Comment by magtimmermans** [comment]
Dat blijft het zelfde. Als de trigger afgaat en het is tussen 16.30 en 8.30 dan. Deze trigger gaat nooit af. Tenzij je bedoelt tussen 8.30 en 16.30

**Comment by JeeMBe** [comment]
Nee, ik wil tussen zonsondergang en zonsopkomst, als de bewegingsmelder beweging detecteert, een actie uit laten uitvoeren. Ik begrijp dat dat op die manier niet kan. Heb je misschien een tip /oplossing?

**Comment by magtimmermans** [comment]
Ik zou de zonsondergang en opgang in een variabele stoppen en elke dag updaten en bij zonsopgang een dag erbij tellen en dan vergelijken in uw conditie.

**Comment by JeeMBe** [comment]
Ok. Dank voor de snelle reacties en de oplossingsrichting.

**Comment by JeeMBe** [comment]
Ik probeer nog even 'het is niet tussen zonsopkomst en zonsondergang"..

**Comment by JeeMBe** [comment]
Opgelost!!  'het is niet tussen zonsopkomst en zonsondergang" werkt. Dank nog voor de tips.
