### ISSUE TITLE
Flow with and... card between Sunset and Sunrise doesn't trigger

### ISSUE THREAD

**Issue by Blaxtar** [magtimmermans/com.cyclone-software.sunevents#53]
If I create a flow with and-card "It Is between Sunset starts and Sunrise ends" the flow fails. At least not after midnight, haven't tried it out before midnight.
![Screen Shot 2022-01-12 at 01 03 28](https://user-images.githubusercontent.com/10800521/149040696-7eb37909-1585-411d-a3f5-b74ae72e2967.png)
Time is 1AM when the screenshot was taken

**Comment by Blaxtar** [comment]
If I invert the card it seems to work :-)
![Screen Shot 2022-01-12 at 01 09 16](https://user-images.githubusercontent.com/10800521/149040964-659e685e-db11-489d-b239-62bbee8b491f.png)

**Comment by magtimmermans** [comment]
Yes, because it compare between today's sunset and sunrise. What think it did was today's sunset and tomorrows sunrise. 
Invert will work.

**Comment by Blaxtar** [comment]
Thanks for a quick reply and a wonderful app! Not an issue then, I've inverted all my cards and now it seems to work flawless :-)
