### ISSUE TITLE
Some incorrect English translations 

### ISSUE THREAD

**Issue by PeterKawa** [magtimmermans/com.cyclone-software.sunevents#55]
Hi Marcel, 

I just 'stumbled upon' a few incorrect English translations.
In the AND section, there are cards like "Azimuth Smaller then value X"
"THEN" should be "THAN" imho.
![sun_events](https://user-images.githubusercontent.com/74005072/159537537-16c1c8b6-e07d-42c9-8a40-3ba329f01853.png)

Best regards,
Peter

**Comment by magtimmermans** [comment]
Thanks. I will fix this asap.

**Comment by magtimmermans** [comment]
fixed in next release
