### ISSUE TITLE
Azimut values incorrect

### ISSUE THREAD

**Issue by Joost2** [magtimmermans/com.cyclone-software.sunevents#56]
Hi, thanks for this great App. When I check (May 9th) the azimut value on Solar events and then on sunearthtools.com, there a difference of 15, one hour (Solar events is too late). Where does the App get his data from, is there a way to correct this (potentially the position on the globe is wrong)? Thanks for your help!

**Comment by magtimmermans** [comment]
I am using the same calculation as in https://www.suncalc.org/

**Comment by Joost2** [comment]
There's a one-hour difference between https://www.sunearthtools.com and  https://www.suncalc.org/. According to my solar-panel production, the sun culminates around 12:45, which is one hour earlier than what is indicated on the suncalc.org site and corresponds to sunearthtools.

**Comment by dirkg173** [comment]
I use the [SunSurveyor](https://www.sunsurveyor.com) App and it shows the same values like the Homey Sunevents App.
Maybe there is a difference because the UTC time isn't correct on https://www.sunearthtools.com.

Another possible point, with Homey firmware v7.4.x Node.js v16 is used. And with Node.js v16 the timecode changed as I read in the forum and on Slack. @magtimmermans, I'm not a programmer but could this be a possible reason?

**Comment by magtimmermans** [comment]
I think indeed that https://www.sunearthtools.com/ incorrect because of the wrong time zone . If I compare this with home assistant (default build in) then they are the same as well. Also several other tools have the same value. If I check when my backyard gets sun it is correct. I could be wrong but I think that https://www.sunearthtools.com/ use gmt+0 I instead of CET.

**Comment by Joost2** [comment]
I finished up using “event nadir with offset of x minutes", x being calculated separately and stored as a variable. However, it didn’t work. The “filtration nadir…” variable was 401, but my pool pump didn’t turn on around 9, as would be expected. I re-tested with a (numerical) variable of which I manually determined the value and again no action. Why’s that ?

Thanks !

Joost

**Comment by magtimmermans** [comment]
That's a known issue in Homey. That variables are not fleeting up correctly. Infact this issue (if I understands you correctly) is already open for more then a year :( very frustrating. It seems difficult to fix. 

I think you can better store both into a var and have an automation that checks when the event is changed and conditions are met and then execute what you want. Kind of complex but that the way around the bug.

**Comment by Joost2** [comment]
Needs to be fixed though, where "can I complain” about this handicapping issue ? Thanks for, as always, your rapid answer, very helpful (even if it did not solve my problem). Joost

**Comment by magtimmermans** [comment]
https://github.com/athombv/homey-apps-sdk-issues/issues/204

**Comment by Joost2** [comment]
I tried with a fixed number:


Why the “number” field is red instead of blue ? It will accept the number, but still…  Is there a limit? The number indicates minutes, right?

**Comment by magtimmermans** [comment]
Hi, yes limit is 60 minutes

**Comment by Joost2** [comment]
You can’t make that 24 hours? It should really help. Well, directly entering 470 minutes actually works fine, but doing that via a variable doesn’t, could that be the issue?

**Comment by Joost2** [comment]
In any case with a variable with a fixed value of 50 it still doesn't work but it won’t harm to increase the limit, in case a solution will be found. Thanks again !

> You can’t make that 24 hours? It should really help. Well, directly entering 470 minutes actually works fine, but doing that via a variable doesn’t, could that be the issue?
>

**Comment by magtimmermans** [comment]
Okay, when I have some time I will check if this is possible to update. The var issue I am depending on homey dev team.

**Comment by magtimmermans** [comment]
I cannot make it 24 hours as in interfering with the next event.
