### ISSUE TITLE
Night start & end seems incorrect

### ISSUE THREAD

**Issue by PeterKawa** [magtimmermans/com.cyclone-software.sunevents#57]
App v0.8.3
Homey v7.3.0

Hi,
Night start & end seem incorrect
![Screenshot_20220517-163225_Homey](https://user-images.githubusercontent.com/74005072/168837806-2e41570e-2890-4fac-8223-e636df26ec94.jpg)

**Comment by magtimmermans** [comment]
No this is correct. Towards summer time there are no values for this. The sun is not going that deep. There for this dare so that people can still calculate with it.

**Comment by PeterKawa** [comment]
I see! Thanks for explaining.
