### ISSUE TITLE
How to use Circadian lightning

### ISSUE THREAD

**Issue by Niekvb-homey** [magtimmermans/com.cyclone-software.sunevents#58]
Hi Developer,

In your description you're referring to circadian lightning.
Could you please explain how I can use this?

Thank you in advance
Yours faithfully
Niek

"- Carcadian lighting:
  Circadian Lighting slowly (imperceivably) adjusts your lights to simulate the natural color temperature shift of daylight throughout a day. 
  This gives your environment a more natural feel, with cooler whites during the midday and warmer tints near twilight and dawn. 
  Circadian Lighting does not account for actual current outdoor conditions, as this could negate the potential health benefits of maintaining a Circadian Rhythm.
  For know you can find the Color Temperature (RGB and Kelvin) as Tokens (until I find a better approach)"

**Comment by magtimmermans** [comment]
Not really. It is depended on your app that controls the lights if you can sent RGB values as variables.
