### ISSUE TITLE
Louvre roof

### ISSUE THREAD

**Issue by Dkoster01** [magtimmermans/com.cyclone-software.sunevents#60]
Hi Marcel,

While I was trying to make a flow with you app and the my livium louvre (Sompfy) roof, i failed to program the angle of the louvre allong with the hight and or angle of the sun. Is there a way to do this? Like every half hour check sun hight and adjust angle louvre?

Kind regards,
Dennis

**Comment by magtimmermans** [comment]
I think you should be able to do this but I have no experience with livium louvre app. With the azimuth and height you you have the ingredients to make this happen.  Of course you need to make some calculations to do this. With some helpers I think it is possible and I suppose you can enter the tilt of the roof in the livium Louvre app for homey?

**Comment by Dkoster01** [comment]
Well, the Livium louvre roof has Sompfy i/o engines and is therefore using the Somfy app (Tahoma). This Tahoma app can tilt the louvres in %.  I will try to programm the % with the Azimuth and height like you suggested. It will become even more complex when the rainsenor is installed.

**Comment by magtimmermans** [comment]
Maybe using homey script would be easier to do.
