### ISSUE TITLE
Compatibility with Homey Cloud

### ISSUE THREAD

**Issue by chimpinwetsuit** [magtimmermans/com.cyclone-software.sunevents#61]
This is a feature request. I missed this app after joining the Homey (Cloud) beta.
How-to information here:
https://apps.developer.homey.app/guides/homey-cloud

**Comment by magtimmermans** [comment]
I will not do this as it requires a Homey Verified Developer account. This is for me just for fun and I am not investing money on this as I use privately now Home Assistant as it gives me more freedom.
