### ISSUE TITLE
The "It isn't after sunrise" seems reversed somehow. (v1.0.0 test)

### ISSUE THREAD

**Issue by PeterKawa** [magtimmermans/com.cyclone-software.sunevents#63]
Hi Marcel, 
Since v1.0.0 test
The "It isn't after sunrise" seems reversed somehow.
![Screenshot_20221024-132550_Homey](https://user-images.githubusercontent.com/74005072/197517507-bada04e9-9a52-46fc-8ec0-dcc57c9b763b.jpg)

Thanks 4 gr8 app and SDK3 upgrade!

**Comment by magtimmermans** [comment]
Good catch. Update will be there after 1 hour.

**Comment by magtimmermans** [comment]
published

**Comment by PeterKawa** [comment]
Thanks for quick fix!
