### ISSUE TITLE
v1.0.0 test: Trigger "Sunset starts" with offset other than 0 doesn't seem to trigger

### ISSUE THREAD

**Issue by PeterKawa** [magtimmermans/com.cyclone-software.sunevents#64]
Hi Marcel,

A flow did not start tonight when running v1.0.0 test.
Triggercard used: "Event 'sunset starts' ". It had offset 12;
_An other flow did run however, it had offset 0._

![Screenshot from 2022-10-24 18-48-08](https://user-images.githubusercontent.com/74005072/197581168-686f90fc-70ca-408f-bc4b-772bf09ec242.png)

Thanks, Peter

**Comment by magtimmermans** [comment]
Hopefully fixed.

https://homey.app/a/com.cyclone-software.sunevents/test/

**Comment by PeterKawa** [comment]
Sorry for the late response, Marcel, yes it seems to run fine again, using the test version.

**Comment by magtimmermans** [comment]
Thanks for the feedback!
