### ISSUE TITLE
off-line

### ISSUE THREAD

**Issue by djbakker** [magtimmermans/com.cyclone-software.sunevents#66]
Hi,
i've a question, is it possible to use this app off-line?
Thanx in request
Douwe-Jan

**Comment by magtimmermans** [comment]
It doesn't require any internet connection.

**Comment by djbakker** [comment]
Top! ThnxDouwe-JanOp 1 nov. 2022 om 17:29 heeft magtimmermans ***@***.***> het volgende geschreven:﻿
It doesn't require any internet connection.
