### ISSUE TITLE
Updated for the new Pro?

### ISSUE THREAD

**Issue by n808** [magtimmermans/com.cyclone-software.sunevents#67]
Will this app be updated to support the new Pro? 
I sincerely hope so, it has functionality that is really useful for several flows that I want to run on times related to sunset and sunrise.

**Comment by dirkg173** [comment]
There are already 2 closed requests regarding SDK3/Homey Pro 2023, and in the app store there is already a [test version](https://homey.app/en-us/app/com.cyclone-software.sunevents/Sun-Events/test/) available.

**Comment by n808** [comment]
Thanks! I apologize for not reading through the closed issues.
