### ISSUE TITLE
new Homey Early2013

### ISSUE THREAD

**Issue by MalerBert** [magtimmermans/com.cyclone-software.sunevents#68]
Avond Marcel,

Bij jouw prima app die door velen dagelijks wordt gebruikt schrijft Homey dat deze app niet compatibel is met de nog uit te leveren Homey Pro (Early 2023).
Er staat "Deze app is verouderd en vereist een update om op Homey Pro (Early 2023) te kunnen werken. Kom in actie door contact op te nemen met de ontwikkelaar." Nou, hier ben ik dan. Ben jij nog van plan om de aanpassingen te doen die de nieuwe Homey nodig heeft of betekent dit het einde voor veel scripts van alle mensen die de nieuwe Homey hebben aangeschaft. Ik ben reuze nieuwsgierig naar jouw antwoord. Ik hoop alleen niet dat ik de xste persoon ben die die vraag bij jou neerlegt. Bij de issues zag ik nog maar één ding staan. En dat was een vertaling en niet de Early 2023.
Vriendelijke groet,
Bert van der Lugt Melsert (bvdlm@live.nl)

**Comment by magtimmermans** [comment]
Hoi,
Hier vind je meer info:

https://community.homey.app/t/app-pro-sun-events-update-sdk3/71043

**Comment by MalerBert** [comment]
dank voor jouw antwoord Marcel
en mooi dat je de software beter maakt (onderhoudbaarheid is zeer belangrijk) en ook laat draaien op de nieuwe Homey
ik heb een bedragje overgemaakt als toon van mijn waardering voor jouw werk

Vriendelijke groet,

 Bert

Op 24 nov. 2022 om 19:10 heeft magtimmermans ***@***.***> het volgende geschreven:

﻿

Hoi,
Hier vind je meer info:

https://community.homey.app/t/app-pro-sun-events-update-sdk3/71043<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcommunity.homey.app%2Ft%2Fapp-pro-sun-events-update-sdk3%2F71043&data=05%7C01%7C%7C41b8d05b7e7243b3ea1208dace4724f1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638049102196399783%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=u6wnpbqzBbifWN%2FleW%2FQFKhJVlQDIqI3ULeZUj%2BXIgk%3D&reserved=0>

**Comment by magtimmermans** [comment]
Enorm bedankt voor je bijdrage!!
