### ISSUE TITLE
Homey pro 2023

### ISSUE THREAD

**Issue by Elmago27310** [magtimmermans/com.cyclone-software.sunevents#69]
Hello, are you thinking about updating your application for homey pro 2023?

**Comment by magtimmermans** [comment]
That already done. Please load the test version.

**Comment by Elmago27310** [comment]
Cool, how do I do that?

**Comment by Elmago27310** [comment]
There must be some translation problems in French, do you want me to check these?

![image](https://user-images.githubusercontent.com/87359247/212025246-bac90a08-bf47-4ab7-b081-7f0e23578b72.png)

**Comment by magtimmermans** [comment]
Yes, please. Can i sent you the translation file so that you can check?

**Comment by magtimmermans** [comment]
Test applications are just at the normal appstore link with test behind.

https://homey.app/en-us/app/com.cyclone-software.sunevents/Sun-Events/test/

There is one failure in it regarding utc/local issue with darkest night and will be updated today/tomorrow.

Marcel Timmermans
Send from my iphone


Op 12 jan. 2023 om 10:06 heeft Elmago27310 ***@***.***> het volgende geschreven:

﻿

Cool, how do I do that?

**Comment by Elmago27310** [comment]
Can you give me the file to translate ?

**Comment by magtimmermans** [comment]
[fr.zip](https://github.com/magtimmermans/com.cyclone-software.sunevents/files/10402470/fr.zip)
Attached the file to translate

**Comment by Elmago27310** [comment]
Hello, I looked at this file but it seems amazing, it seems to me correct.

Why have the same condition twice?
![image](https://user-images.githubusercontent.com/87359247/212121722-55ff9abb-bfbd-4b89-9e72-8660953765cc.png)

**Comment by magtimmermans** [comment]
I don't speak french. Not sure what is on the card. Is this a condition card? And us this the test version?

**Comment by Elmago27310** [comment]
ok, I’m checking your files, I’ve modified some on girthub

**Comment by Elmago27310** [comment]
Yes, I use the test version but the problem was the before. it’s a "When" card

I did some translation again but the problem is not there. Could you tell me if in your language you have the same problem?

**Comment by magtimmermans** [comment]
No i dont have a duplicate if that's what you mean

**Comment by Elmago27310** [comment]
No I think nothing, I’m looking for where it may come from
