### ISSUE TITLE
Avondscherming usage in advanced flow

### ISSUE THREAD

**Issue by chrisboer** [magtimmermans/com.cyclone-software.sunevents#70]
Advanced flow 

![image](https://user-images.githubusercontent.com/23163409/214724557-3d6a465b-340d-4847-a1e7-b463715e18f1.png)

It is after Avond schemering and it gives false ? 

Until what time this will be true ?  It is now 01:22 in the night

**Comment by magtimmermans** [comment]
Beste Chris,

Gebruik je de laatste test versie?

https://homey.app/nl-nl/app/com.cyclone-software.sunevents/Zonnestanden/test/

En wat gebruik je als trigger?

Hij blijft actief tot middennacht.

Marcel Timmermans
Send from my iphone


Op 26 jan. 2023 om 01:22 heeft Chris Boer ***@***.***> het volgende geschreven:

﻿

Advanced flow

[image]<https://user-images.githubusercontent.com/23163409/214724557-3d6a465b-340d-4847-a1e7-b463715e18f1.png>

It is after Avond schemering and it gives false ?

Until what time this will be true ?
