### ISSUE TITLE
evetTimes is not defined

### ISSUE THREAD

**Issue by NdyGen** [magtimmermans/com.cyclone-software.sunevents#71]
Since the update to version 1.3.0 the card "it is before" (het is voor) generates the error "eventTimes is not defined" 

I'm using the sunrise event and time offset 0

**Comment by aswespeak** [comment]
Same for lots of us. After the update some flows get the error ”Event time not defined”.
Lots of people in homey facebook group confirms this.

**Comment by magtimmermans** [comment]
Wierd, as this version was in test for 2 months. I will check the issue.

**Comment by aswespeak** [comment]
After som more testing it seems to apply for the card ”It is before”. Other cards like ”it is after” is functioning.

**Comment by magtimmermans** [comment]
Hi,
Could you test this version, then I will publish it after okay.

https://homey.app/a/com.cyclone-software.sunevents/test/

**Comment by aswespeak** [comment]
Will give it a go after 18.00👍
