### ISSUE TITLE
Sunevent nadir not working as trigger

### ISSUE THREAD

**Issue by JoakimBjorn** [magtimmermans/com.cyclone-software.sunevents#72]
The sun event "nadir" is not longer working as a trigger for me. It does not show up in the trigger list in the app configuration.

If I use another sun event it works fine but never with "nadir".

I am using advanced flow.

**Comment by magtimmermans** [comment]
Which version of the app?

**Comment by JoakimBjorn** [comment]
Version 1.3.1

**Comment by magtimmermans** [comment]
Please install the latest test version:

https://homey.app/nl-nl/app/com.cyclone-software.sunevents/Zonnestanden/test/

**Comment by JoakimBjorn** [comment]
With experimental version it seems to work. Nadir shows up in my triggers but with the wrong time?
In my flow I use nadir with offset -60.
![Screenshot_20230216_093508_Homey](https://user-images.githubusercontent.com/91701728/219312306-f29fb901-12b7-437f-88ad-b66e3a07961a.jpg)
![Screenshot_20230216_092944_Homey](https://user-images.githubusercontent.com/91701728/219312459-3bffc452-3c04-4c73-9277-3783aba95c6a.jpg)

**Comment by magtimmermans** [comment]
I think it is a display issue a will run on time. But I will fix it.
