### ISSUE TITLE
lightintintensity changed factor 10 after update to 1.4.5

### ISSUE THREAD

**Issue by fafrits** [magtimmermans/com.cyclone-software.sunevents#73]
For your information.
After the update of the sunevent app for Homey to vs 1.4.5 the lightintensity parameter changed more then a factor 10. I have the feeling that this is a little bug.
If it is an error, please would you repair it, otherwise we'll have to accept and addapt the parameter used in the Homey flows.

**Comment by magtimmermans** [comment]
Thats indeed changed. I got a number of requests to have the light percentage in 0-100 and the brightness in 0-1. Some devices require the first one other the later.
