### ISSUE TITLE
Missing Icon on FlowCard

### ISSUE THREAD

**Issue by CyberSponk** [magtimmermans/com.cyclone-software.sunevents#74]
The Icon for Sunevents not shown on Flowcards:

![IMG_6045](https://user-images.githubusercontent.com/26149030/233823165-3c46bf72-41eb-4450-b29e-305e5ffd00ea.jpeg)

Homey 10.0.0-rc.78 / Homey iOS App 7.0.0.1185 / Sunevents App 1.4.5

**Comment by magtimmermans** [comment]
Seems a problem from os 10

**Comment by dirkg173** [comment]
Crosschecked:
Homey 2019 / FW 8.1.3 / iOS App 7.0.0.1185 / Sunevent 2.1.1 (Experimentell) -> no problem
Homey 2023 / FW 10.0.0-rc.78 / iOS App 7.0.0.1185 / Sunevent 2.1.1 (Experimentell) -> problem
