### ISSUE TITLE
Conditional card It [is|isn't] after sunrise/sunset is inverted

### ISSUE THREAD

**Issue by PeterKawa** [magtimmermans/com.cyclone-software.sunevents#75]
Hi Marcel, 

Homey Pro 2019 v8.1.3 (since release)
Sun Events v2.1.1 (since release)
Diag: `255f6a5c-3fe3-4824-a0a4-a06155cedb11`

A few days ago I started to notice lights turned on, or didn't turn on while they should at that time of day/night. I took a closer look at the flows involved, and the conditional card 'It [is|isn´t] after sunrise/sunset' card seems to be inverted now? 

FWIK I didn't change anything recently, or it has to be this:
Several days ago I temporary changed the timezone to the US for a test. I changed it back after a minute, and the time & timezone are correct (NL UTC+2) when I look at the system settings;
AND, Homey was restarted 3 days ago (note, I seldom restart Homey)

For clarity i've added the laptop clock on the screenshots, and Homey's time & timezone are correct:
![Screenshot from 2023-06-09 13-06-40](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/74005072/a80d3792-49ad-4b1b-a2a7-c8638bb54891)

![Screenshot from 2023-06-09 13-08-16](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/74005072/40db8fa5-718e-4be4-a848-b1d01342c314)

![Screenshot from 2023-06-09 13-14-37](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/74005072/d643287c-0ef4-4993-adb4-3190a59b5bef)

![Screenshot from 2023-06-09 13-31-32](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/74005072/28f62183-3773-4732-8ec6-a753abe8fdbc)

![Screenshot from 2023-06-09 13-16-05](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/74005072/6de159c9-a30b-4bbc-b7db-ad2cddc2c3d5)

![Screenshot from 2023-06-09 13-39-59](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/74005072/e912fdee-5b5f-4e71-ae23-f82b1e8384c7)

Best, and again many thanks for the great app!
Peter

**Comment by magtimmermans** [comment]
I have published a new version which should fix it.

https://homey.app/nl-nl/app/com.cyclone-software.sunevents/Zonnestanden/test/

**Comment by PeterKawa** [comment]
Installed the test version, but it still seems to  error, sorry:
![Screenshot_20230619-154510_Homey.jpg](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/74005072/1e0d01bb-0224-4e96-8d43-d3cbdc31bf53)

Homey's time:
![Screenshot_20230619-155645_Homey.jpg](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/74005072/a7a3c097-a9d4-4ad6-9ae9-94fbf39c5917)

**Comment by magtimmermans** [comment]
Forgot to commit. Must be okay now. Please install new test version

**Comment by PeterKawa** [comment]
Thanks, it's OK now. Thanks for looking into this. Much appreciated.
