### ISSUE TITLE
feature request: trigger events

### ISSUE THREAD

**Issue by B3rt** [magtimmermans/com.cyclone-software.sunevents#76]
Is it possible to add the trigger time events (listed in the configuration page) to be available as tags or logic values?

It would be nice to see via tags when a trigger time should run, using betterlogic app it would be possibl to display the trigger time on a button so you can see when the next trigger would be executed.

**Comment by magtimmermans** [comment]
Hi,

I will put this on my to do list.

**Comment by magtimmermans** [comment]
I was looking into this. I am not sure I completely understand you. Every event has already a tag with the time stamp.

**Comment by B3rt** [comment]
I want to know/use the time and name of the trigger.
When you open the configuration menu in Homey of the app there is a tab called triggers, here are all next triggers listed which are used in flows.

It would be nice if there where logic values (or tag cards) of these triggers.
I could use them to show as text in homey, for example:
Curtains wil open at: <tag trigger 'ochtendschemering'  time>
So tags or logicvalues of all the triggers.

**Comment by magtimmermans** [comment]
They are already there.
