### ISSUE TITLE
Einde nacht event is off

### ISSUE THREAD

**Issue by Vetjes** [magtimmermans/com.cyclone-software.sunevents#77]
Hi, the event for night starts and night ends are both defined as 1/Jan/1970. This makes my flows act weird as you can imagine. 
![IMG_2542](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/86045790/20d53833-4d33-45ca-841d-1c4048936273)

**Comment by magtimmermans** [comment]
In the summer there is no position of the sun that give a time. Thats the reason.
