### ISSUE TITLE
"It's between" does not trigger.

### ISSUE THREAD

**Issue by 2Sudden** [magtimmermans/com.cyclone-software.sunevents#79]
I’m using Homey Pro 2023, in advanced flows I can’t get It’s between (sunset,0 and sunrise,0) to work. If I use a fixed time it launches ok. I’m just guessing but, could it have some thing to do with the fact that there is a date change between the two trigger values?

![image](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/44867473/94ff2034-b8ce-401b-8e04-0e8193821f53)

Thanks for a great application!

**Comment by magtimmermans** [comment]
That's because sunset and sunrise is the one from today. You would like to see between sunset today and sunrise tomorrow. That's unfortunate not working. I am working on a mechanism that it always take the next event after current time. But that will take a few weeks.
