### ISSUE TITLE
It's between is not working

### ISSUE THREAD

**Issue by iBosvelt** [magtimmermans/com.cyclone-software.sunevents#80]
Hi Marcel,

First of all great app, but i have issues with the AND-"its between" card.
Im using this card for the condition one hour before and one hour after sunset.
<img width="200" alt="image" src="https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/139918699/cfb3bacf-9508-4129-bff9-927b3137e424">
At this moment it 21.33. 

I suppose this card should be false? 
Im running the 1.4.7 test version on my HP23.

Thanks! 
iBosvelt

**Comment by iBosvelt** [comment]
after update i had to re-add the card. now it seems to work :)

**Comment by 2Sudden** [comment]
I upgraded to 1.4.7 but i still experience the same problem.
![image](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/44867473/3e0b3cfa-ef2e-4fa7-9dad-7053f0c65650)
This test was done 1 hour after sunset. I also created a new flow from scratch.

**Comment by magtimmermans** [comment]
What is tested is the following
For example is it between today at 21.30 (sunset) and today (6.30) sunrise. 

If you test this at 22.00 the result is false. I think this is always false.

**Comment by 2Sudden** [comment]
I can also confirm if I invert to "isn't between" and run the flow after sunset it triggers as "true"

BR
2sudden
