### ISSUE TITLE
Crashing at the advanced section

### ISSUE THREAD

**Issue by posthok** [magtimmermans/com.cyclone-software.sunevents#83]
When looking in homey at the sun events app and going to advanced to see the trigger moments the homey app crashes in ios

**Comment by magtimmermans** [comment]
Please try https://homey.app/en-us/app/com.cyclone-software.sunevents/Sun-Events/test/

**Comment by posthok** [comment]
Had ik al gedaan. En ook hier wanneer ik in de app naar app instellingen ga crashed de homey app

Met vriendelijke groet,
Peter Post
________________________________
Van: magtimmermans ***@***.***>
Verzonden: Tuesday, November 7, 2023 12:12:48 PM
Aan: magtimmermans/com.cyclone-software.sunevents ***@***.***>
CC: Peter ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.sunevents] Crashing at the advanced section (Issue #83)


Please try https://homey.app/en-us/app/com.cyclone-software.sunevents/Sun-Events/test/

**Comment by magtimmermans** [comment]
Hoi,


Vreemd, ik heb nergens last van. Welke versie van de app gebruik je?


________________________________

**Comment by posthok** [comment]
Hoi.
De laatste 10.1.0 rc2

Met vriendelijke groet,
Peter Post
________________________________
Van: magtimmermans ***@***.***>
Verzonden: Tuesday, November 7, 2023 1:05:00 PM
Aan: magtimmermans/com.cyclone-software.sunevents ***@***.***>
CC: Peter ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.sunevents] Crashing at the advanced section (Issue #83)


Hoi,


Vreemd, ik heb nergens last van. Welke versie van de app gebruik je?


________________________________

**Comment by posthok** [comment]
Met vriendelijke groet,
Peter Post
________________________________
Van: magtimmermans ***@***.***>
Verzonden: Tuesday, November 7, 2023 1:05:00 PM
Aan: magtimmermans/com.cyclone-software.sunevents ***@***.***>
CC: Peter ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.sunevents] Crashing at the advanced section (Issue #83)


Hoi,


Vreemd, ik heb nergens last van. Welke versie van de app gebruik je?


________________________________

**Comment by magtimmermans** [comment]
Hoi Peter,

Dat is de homey versie. I mean the app version 7.xx

Marcel Timmermans
Send from my iphone


Op 7 nov. 2023 om 13:11 heeft Peter ***@***.***> het volgende geschreven:

﻿

Hoi.
De laatste 10.1.0 rc2

Met vriendelijke groet,
Peter Post
________________________________
Van: magtimmermans ***@***.***>
Verzonden: Tuesday, November 7, 2023 1:05:00 PM
Aan: magtimmermans/com.cyclone-software.sunevents ***@***.***>
CC: Peter ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.sunevents] Crashing at the advanced section (Issue #83)


Hoi,


Vreemd, ik heb nergens last van. Welke versie van de app gebruik je?


________________________________

**Comment by posthok** [comment]
Ja op de foto die ik mee gestuurd heb.
7.6.0.1348

Met vriendelijke groet,
Peter Post
________________________________
Van: magtimmermans ***@***.***>
Verzonden: Tuesday, November 7, 2023 5:25:37 PM
Aan: magtimmermans/com.cyclone-software.sunevents ***@***.***>
CC: Peter ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.sunevents] Crashing at the advanced section (Issue #83)


Hoi Peter,

Dat is de homey versie. I mean the app version 7.xx

Marcel Timmermans
Send from my iphone


Op 7 nov. 2023 om 13:11 heeft Peter ***@***.***> het volgende geschreven:

﻿

Hoi.
De laatste 10.1.0 rc2

Met vriendelijke groet,
Peter Post
________________________________
Van: magtimmermans ***@***.***>
Verzonden: Tuesday, November 7, 2023 1:05:00 PM
Aan: magtimmermans/com.cyclone-software.sunevents ***@***.***>
CC: Peter ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.sunevents] Crashing at the advanced section (Issue #83)


Hoi,


Vreemd, ik heb nergens last van. Welke versie van de app gebruik je?


________________________________

**Comment by magtimmermans** [comment]
Kan aan mij liggen maar ik zie geen foto 😊

**Comment by posthok** [comment]
Deze had ik in een mail naar je gestuurd

Met vriendelijke groet,
Peter Post
________________________________
Van: magtimmermans ***@***.***>
Verzonden: Wednesday, November 8, 2023 8:08:41 AM
Aan: magtimmermans/com.cyclone-software.sunevents ***@***.***>
CC: Peter ***@***.***>; Author ***@***.***>
Onderwerp: Re: [magtimmermans/com.cyclone-software.sunevents] Crashing at the advanced section (Issue #83)


Kan aan mij liggen maar ik zie geen foto 😊
