### ISSUE TITLE
For Homey Pro 2023 flow the trigger “Darkest moment of the night” is not get activated

### ISSUE THREAD

**Issue by GoodA3** [magtimmermans/com.cyclone-software.sunevents#84]
Installed on HP 2023 the app Sun Events. 

Using the event “Darkest moment of the night” the trigger is not activated since a while. My assumption is this is happening since the activation of the winter time. 

Please validate this issue?

Thanks in advance

**Comment by magtimmermans** [comment]
Yes, correct!
