### ISSUE TITLE
Offset 0 min not working

### ISSUE THREAD

**Issue by frojds** [magtimmermans/com.cyclone-software.sunevents#85]
When I use **Event _Event_ with offset _Offset in minutes_** and set Offset to 0 (zero), direct in the event or from a Variable, the event will not run.
Overall it's a very nice app!

**Comment by frojds** [comment]
Not with negative values aswell. My workaround will be to make personal events.

**Comment by magtimmermans** [comment]
Are you using the latest app?
https://homey.app/en-us/app/com.cyclone-software.sunevents/Sun-Events/test/

**Comment by frojds** [comment]
Thanks for prompt answer. I did not use latest app version as it was marked Test but I have now downloaded and use it.

It seem that the app work fine except that it is not possible to use a variable in Event Event with offset Offset in minutes.

If I set the offset as a number it seem to work but not with the same value in a numeric variable.

That was most likely the reason for my first posts.

Example from the Log : 2023-12-05T14:22:28.630Z [log] execute: sunsetStart at Invalid Date offset [[homey:manager:logic|d34ce……]]

**Comment by magtimmermans** [comment]
Hi, unfortunately that I cannot change and is a problem from homey os. There is a case for this but seems to be a low prio as it is already open for quite some time.

**Comment by frojds** [comment]
OK, I see. Would be helpful if this was mentioned in app descriptions.

**Comment by magtimmermans** [comment]
Thanks for the tip.
