### ISSUE TITLE
Android keyboard missing minus

### ISSUE THREAD

**Issue by foretix** [magtimmermans/com.cyclone-software.sunevents#86]
Hi,
on Android 12 Homey app when I want to define my own events in settings of Sun Events app, the field to enter numerical degrees triggers numerical keyboard, but minus sign is missing on this keyboard.

![Screenshot_20240128_101957_Homey](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/15965898/52bae47e-be19-42e1-a5e7-80f64cfa0219)

Workaround is to enter number in the next field and cut/paste it.

**Comment by magtimmermans** [comment]
Still looking, I do not have an android :(

**Comment by foretix** [comment]
I tested for you different variants of input, because I'm not sure which variant is rendered in index.html. From the variants below, only 2 renders minus, dot, and comma. 3-5 are same as my screenshot above with dot and comma. Number 1 is just test. It shows many phone related characters. Hope it helps you.

```html
1.<input type="text" inputmode="tel" name="number"/><br>
2.<input type="text" inputmode="numeric" name="number"/><br>
3.<input type="text" inputmode="decimal" name="number"/><br>
4.<input type="number" inputmode="numeric" name="number"/><br>
5.<input type="number" inputmode="decimal" name="number"/>
```

**Comment by magtimmermans** [comment]
Hi, Thanks. I am using angularjs and this seems to be an issue. I have now made it a text keyboard with validation.
https://homey.app/a/com.cyclone-software.sunevents/test/
