### ISSUE TITLE
Trigger not working anymore. 

### ISSUE THREAD

**Issue by djmaupp** [magtimmermans/com.cyclone-software.sunevents#88]
Hi. 

I’m using the trigger between “Ochtendschemering” and Einde ochtend gouden uur. But since a few days this is not working. Even when I click the test button between set times. (See screenshot)

![IMG_8561](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/116944608/0d3b4468-95a9-4c98-86c6-df84a0e58263)
![IMG_8560](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/116944608/40ce5190-895e-4f28-a3ea-f284add617f5)
![IMG_8562](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/116944608/9f94b207-3d53-4b9d-8541-6a8c4679d4ca)

**Comment by djmaupp** [comment]
Seems to be working after again restarting the app

**Comment by magtimmermans** [comment]
You could also maybe download the latest test version.
