### ISSUE TITLE
French translation error

### ISSUE THREAD

**Issue by L1ttleP00l** [magtimmermans/com.cyclone-software.sunevents#89]
Hello,
I would like to inform you that there is a translation error concerning one of the "And" cards.
The "After" and "Before" cards are both called "Before".
I have carried out tests on my box and I can confirm that the error comes from the first card as I have circled it on the screenshot.
This card should be switched to "After".
Thank you for taking my request into account.
Sincerely

![Cards](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/132281084/7a707bd0-ab20-4436-8bff-5440a06d8fa8)

**Comment by magtimmermans** [comment]
Could you let me know the French word?

**Comment by L1ttleP00l** [comment]
Of course! The term used is "C'est après". Thanks for the quick feedback.

**Comment by magtimmermans** [comment]
Hi, I checked all the code but this seems okay. Which version are you using?

**Comment by L1ttleP00l** [comment]
Hi, I'm using the latest version (1.4.8). The application is always up to date.
![Capture d’écran du 2024-03-24 17-40-36](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/132281084/2da131d3-6deb-4658-a9fc-022293dd2d57)
![Capture d’écran du 2024-03-24 17-40-07](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/132281084/3f6ddee3-3dc3-45af-8b33-032e38d64fc5)

**Comment by magtimmermans** [comment]
Please check the latest test version: https://homey.app/a/com.cyclone-software.sunevents/test/

**Comment by L1ttleP00l** [comment]
Hello,

I've just installed and tried this version 2.1.3 and it works fine for me. The problem is solved.

Thank you for your reactivity.
