### ISSUE TITLE
Request: Azimuth

### ISSUE THREAD

**Issue by gajdur** [magtimmermans/com.cyclone-software.sunevents#9]
Hi @magtimmermans, any chance to include the Sun Azimuth as variable? Tnx.

**Comment by magtimmermans** [comment]
Hi,

It is on my to do list only I have not much time lately.

Marcel Timmermans
Send from my iphone


Op 16 jun. 2017 om 14:54 heeft viktor <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi @magtimmermans<https://github.com/magtimmermans>, any chance to include the Sun Azimuth as variable? Tnx.

**Comment by magtimmermans** [comment]
Done

**Comment by gajdur** [comment]
Hi and tnx for including the Azimuth. Unfortunately, is always showing 233 degrees. Tried with manual and automatic Location, no success.

**Comment by magtimmermans** [comment]
Yes, is correct. I have changed this already. No I am testing with Altitude as well. If everything is ok. I will release it tomorrow.
