### ISSUE TITLE
The night begins function returns true in the middle of the day

### ISSUE THREAD

**Issue by pp5d2** [magtimmermans/com.cyclone-software.sunevents#90]
Hi,

the night begins (0) returns true while we have 11:15am right now :)

Best,
Peter

**Comment by magtimmermans** [comment]
Where are you located and do you have the coordinates coorect in homey?

**Comment by pp5d2** [comment]
I'm in Germany. I just double-checked that the location is correctly set in Homey. BTW: The rule "before sunset" fires at the same time with "the night begins".

Best,
Peter
Nachricht von magtimmermans ***@***.***> am 19. Mai 2024, 16:56 +0200:

**Comment by magtimmermans** [comment]
Hi,

What is the nearby city from your home?

Can you try use ng the latest test version?

https://homey.app/nl-nl/app/com.cyclone-software.sunevents/Zonnestanden/test/

I am currently on holiday and not able to try.

**Comment by pp5d2** [comment]
Hi - I'm in Minden, Germany. Your beta fixed the issue but introduced another one: Several cards now exit with an error "Oops, Couldn't find event astronomicalDawn".

Freundliche Grüße,
Peter Prahl
Nachricht von magtimmermans ***@***.***> am 20. Mai 2024, 08:49 +0200:

**Comment by magtimmermans** [comment]
That's wierd. The app is installed on more than 15000 homeys. Never had this error.

Can you please tell me what version of homey do you have? Maybe a reboot if homey helps.


Marcel Timmermans
Send from my iphone


Op 21 mei 2024 om 13:23 heeft pp5d2 ***@***.***> het volgende geschreven:

﻿

Hi - I'm in Minden, Germany. Your beta fixed the issue but introduced another one: Several cards now exit with an error "Oops, Couldn't find event astronomicalDawn".

Freundliche Grüße,
Peter Prahl
Nachricht von magtimmermans ***@***.***> am 20. Mai 2024, 08:49 +0200:

**Comment by magtimmermans** [comment]
I cannot reproduce this.
