### ISSUE TITLE
Sun is not set when the sun is set.

### ISSUE THREAD

**Issue by phgmhendrix** [magtimmermans/com.cyclone-software.sunevents#92]
Vague description, but let me explain.
When you trigger on 'sunset' and then check the sunset status with an AND-card, the second one returns false.
Although it is stupid to do this in one flow it should be working nevertheless.

I can clarify in more detail if my issue is not yet completely clear.

**Comment by magtimmermans** [comment]
What do you mean with the status? Could you give an example or screenshots.

**Comment by phgmhendrix** [comment]
Yes, no problem. The flow below:
![image](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/11439882/fd7fb54f-5884-40aa-ba0a-afe319524c03)

Results in the logging below:
![image](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/11439882/92d389d5-754d-46ca-a7a2-d7f938ca074e)

Hopefully this clarifies things a bit.

**Comment by phgmhendrix** [comment]
Please wait a bit and let me test a bit more. I might have changed something and drew the wrong conclusion.
