### ISSUE TITLE
Sun Events Not Working With Withings in Standard or Advanced Flows In HomeyPro2023 Early

### ISSUE THREAD

**Issue by JoelDearing** [magtimmermans/com.cyclone-software.sunevents#93]
Hello,  In its most basic form the advance flow I wrote is When the Withings Sleep devices senses I get into bed, then turn off the light.  Or when I get out of bed, turn on the light.  You can see that in the screenshot labeled "Basic"  It works as it should.
Then I added an "And" condition.  Using the built in Homey Date And Time card, function if the time is between 10:50PM and 7:30 AM. You can see the flow in the screenshot Basic With Date And Time.  This also works as expected.
While the start time of 10:50 pm is good, I would like the end time in the morning to change with the sunrise.  I was told about Sun Events.  It appears to not be working with Withings and the following flows.  I started with very broad sun event, sunset to sunrise.  (Since sunset didn't matter, it could be any time as long it was before 11p.)  You can see that flow with Sun Events 1, it does not do anything.  I then tried creating a standard flow instead of an advanced flow, using the Homey Date & Time card for 10:50p to start the time window, and Sun events to end the time window.  One flow for getting in bed, one flow to get out of bed.  See these screen shots as Get In Bed and Get Out Of Bed  Neither of these work,  I also tried another advance flow where date and time opened the time window, and sun events ended the time window, and that flow did not work either.  Am I missing something, or is there a bug with Sun Events, Withings and Jasco Zwave lights working together.    Thank you in advance for taking a look at this.  Best, Joel

**Comment by magtimmermans** [comment]
I am missing the pictures.  Make sure you have downloaded the latest test version.

**Comment by JoelDearing** [comment]
Take 2
![Basic with Date And Time](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/25068648/36177827-590a-47e7-9b8e-4388960693fc)
![Basic](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/25068648/7db6eb5f-10d6-4950-b014-8402f3b3009c)
![Get In Bed Date_Time Sun Events](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/25068648/4dd34cb8-4c86-43ac-b94d-18ca53832b6f)
![Got Out Of Bed Date_n_Time_Sun Events](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/25068648/993218c6-dbd8-4c91-9944-1ccfe34a6c40)
![Sun Events 1](https://github.com/magtimmermans/com.cyclone-software.sunevents/assets/25068648/f9ded50d-f49e-404c-8c73-1c66f3c35194)

**Comment by magtimmermans** [comment]
You flow 3/4 are never going to work. You are testing if the time is later then 22:52 and before sunrise (which is for example 7.00) this condition will never work.
