### ISSUE TITLE
Please add larger possible OFFSET

### ISSUE THREAD

**Issue by rickroersma** [magtimmermans/com.cyclone-software.sunevents#94]
Hi,

Love your app, it would be perfect if there was a larger possible offset. It is two hours before "begin golden hour", but it is high time to slowly turn on the lights here. However, I can only set a -60 offset.
So please -at least- double the possible OFFSET, to make it easy to have my lights start in time.

Thanks a Lot!

Best regards,

Rick

**Comment by LasseRy** [comment]
I like also have the ability to have a larger offset (as it was before) -60/60 and before I could set -120/120.

Thanks

**Comment by bbrodnik** [comment]
Browser version accepted larger offsets and flows worked fine with offsets of 100 and 200. Resently I wanted to edit existing flow and couldn't save them:

![image](https://github.com/user-attachments/assets/6647cf82-1351-48ff-8bad-ada91d59b72f)

Could you please allow wider offset range to make your excelent app even more usefull?

Thanks and best regards.

**Comment by magtimmermans** [comment]
Larger offset (-120/120)
https://homey.app/nl-nl/app/com.cyclone-software.sunevents/Zonnestanden/test/

**Comment by bbrodnik** [comment]
I installed newest test version and tried, but offset 100 still yields invalid argument error.

 

And besides, what is the downside which prevents you extending offset even more then to -120/120? I would suggest -300/300 or more. It worked fine for me with 200 until some weeks ago.

 

Regards,

Brane

**Comment by magtimmermans** [comment]
https://homey.app/a/com.cyclone-software.sunevents/test/
new version with 120. You can always set a custom angle to get what you want.
