### ISSUE TITLE
Behavior of "it is between event A and event B"

### ISSUE THREAD

**Issue by kukuyamaPlatner** [magtimmermans/com.cyclone-software.sunevents#95]
Hi,

I want to have my outside lights on between the evening golden hour and until the morning golden hour the day after.
I setup the flow as seen in the attached photo:
<img width="1009" alt="Screenshot 2024-08-25 at 0 13 17" src="https://github.com/user-attachments/assets/4283b36c-7ed3-4adc-b0c2-6c08d7087828">

At midnight - I the lights turned off by the flow as can be seen from the log of the light:
<img width="295" alt="Screenshot 2024-08-25 at 0 13 56" src="https://github.com/user-attachments/assets/f602c08c-36bd-402d-b60b-ab51d7237636">

I suspect this is happening since at midnight it's a new day - and it thinks that the evening golden hour for this day haven't started yet.

I think it will make sense for this card to behave similar to the date/time card the time is between - where if the second time is earlier than the first time - it is considered to be the next day:
<img width="317" alt="image" src="https://github.com/user-attachments/assets/96ca7f7b-9d28-4399-b75a-b63596180b0c">

**Comment by magtimmermans** [comment]
Added test for between sunset and sunrise. If this is working I can make it for the rest as well.

https://homey.app/nl-nl/app/com.cyclone-software.sunevents/Zonnestanden/test/

**Comment by b-thieb** [comment]
Dear magtimmermans,
for information, I have the same problem after installing "zonnenstanden 2.2.0" at 0:00, the new day is not taken into account and the status changes without any external action.
For my part, the problem remains.

**Comment by magtimmermans** [comment]
Could you show an example flow?

**Comment by kukuyamaPlatner** [comment]
Hi,

I have installed the test version, without changing my flow which looks
like this:
<img width="739" alt="image" src="https://github.com/user-attachments/assets/9e4262ed-eaee-4a01-aa0d-2b2b79d81ad8" />


at midnight between thursday and friday - the flow was triggered (i'm
guessing since the day was friday, and it was after the sunset of the
previous day - Thursday)
This is not the desired behavior.

Only when i say between sunset and sunrise - i don't want it to reset at
midnight.
But on events with a single time, not a range the time should be relative
to the day of the event.

maybe i have everything wrong here in my analysis.

Thanks very much,
Yair

**Comment by b-thieb** [comment]
Dear magtimmermans,
sorry to respond so late but to get the flow I have to pass 00:00.
before 00h00 flow is 
![image](https://github.com/user-attachments/assets/691de9f7-a774-48ef-8ccf-af74cc00809b)
after is
![image](https://github.com/user-attachments/assets/56c861e2-402e-4211-bfba-ca21a83f4b15)

I test with version 2.2.1, same problem.

regards.

**Comment by magtimmermans** [comment]
2.2.1 is only logging added. Could you sent me this?

**Comment by magtimmermans** [comment]
> Hi, I have installed the test version, without changing my flow which looks like this: <img width="739" alt="image" src="https://github.com/user-attachments/assets/9e4262ed-eaee-4a01-aa0d-2b2b79d81ad8" /> at midnight between thursday and friday - the flow was triggered (i'm guessing since the day was friday, and it was after the sunset of the previous day - Thursday) This is not the desired behavior. Only when i say between sunset and sunrise - i don't want it to reset at midnight. But on events with a single time, not a range the time should be relative to the day of the event. maybe i have everything wrong here in my analysis. Thanks very much, Yair

Exactly at midnight, it should be updated. Could you sent me the logfiles? What will trigger the flow? Could it be exactly on midnight?

**Comment by kukuyamaPlatner** [comment]
Hi,

it triggers every 5 minutes - so i guess exactly at midnight it happens:
<img width="988" alt="image" src="https://github.com/user-attachments/assets/85ef799f-6b22-49b2-ada6-ab654c0cd38d" />

what is updated exactly at midnight on your side ?

**Comment by magtimmermans** [comment]
I found the issue (I will test it tonight) it was because of the Timezone.

**Comment by kukuyamaPlatner** [comment]
is there a new version to test?

**Comment by magtimmermans** [comment]
Yes in test.
